In [2]:
import numpy as np

In [4]:
A = np.array([[1,1,2], [2, 4, -3], [3, 6, -5]])
AB = np.array([[1,1,2, 9], [2, 4, -3, 1], [3, 6, -5, 0]])

In [3]:
A

array([[ 1,  1,  2],
       [ 2,  4, -3],
       [ 3,  6, -5]])

In [5]:
AB

array([[ 1,  1,  2,  9],
       [ 2,  4, -3,  1],
       [ 3,  6, -5,  0]])

In [13]:
np.linalg.inv(A).round(0)

array([[  2., -17.,  11.],
       [ -1.,  11.,  -7.],
       [  0.,   3.,  -2.]])

In [7]:
np.linalg.matrix_rank(A)

3

In [10]:
np.linalg.matrix_rank(AB)

3

In [15]:
A = np.array([[1,2,1,1], [0,1,1,1], [2,2,0,0], [1,0,-1,1]])
AB = np.array([[1,2,1,1,0], [0,1,1,1,1], [2,2,0,0,-2], [1,0,-1,1,-1]])

In [16]:
A

array([[ 1,  2,  1,  1],
       [ 0,  1,  1,  1],
       [ 2,  2,  0,  0],
       [ 1,  0, -1,  1]])

In [17]:
AB

array([[ 1,  2,  1,  1,  0],
       [ 0,  1,  1,  1,  1],
       [ 2,  2,  0,  0, -2],
       [ 1,  0, -1,  1, -1]])

In [19]:
np.linalg.matrix_rank(A)

3

In [20]:
np.linalg.matrix_rank(AB)

3

In [21]:
np.shape(A)

(4, 4)

In [4]:
A = np.array([[1,1], [0,3], [0,4]])
AB = np.array([[1,1,1], [0,3,2], [0,4,3]])

In [5]:
np.linalg.matrix_rank(A)

2

In [6]:
np.linalg.matrix_rank(AB)

3