## Determind compatible systems

In [4]:
# with solve we solve() compatible determind systems
A <- rbind(c(1,1,2), c(2,4,-3), c(3,6,-5))
b <- c(9,1,0)
Ab <- cbind(A, b)

In [5]:
A

[,1] [,2] [,3]
[1,] 1    1     2  
[2,] 2    4    -3  
[3,] 3    6    -5

In [6]:
b

[1] 9 1 0

In [7]:
Ab

b
[1,] 1 1  2 9
[2,] 2 4 -3 1
[3,] 3 6 -5 0

In [10]:
# Ranks

qr(A)$rank == qr(Ab)$rank

[1] TRUE

In [11]:
dim(A)

[1] 3 3

In [12]:
ncol(A)

[1] 3

In [14]:
# If true, then the system is determind complatible, and I will be able apply solve()
qr(A)$rank == ncol(A)

[1] TRUE

In [17]:
sol <- round(solve(A, b), 1)

In [18]:
sol

[1] 1 2 3

In [19]:
# Checking the solution

A %*% sol == b

[,1]
[1,] TRUE
[2,] TRUE
[3,] TRUE

In [30]:
A <- rbind(c(1,2), c(3,0))
B <- rbind(c(9,6), c(15,0))

In [37]:
A

[,1] [,2]
[1,] 1    2   
[2,] 3    0

In [38]:
B

[,1] [,2]
[1,]  9   6   
[2,] 15   0

In [31]:
A.inv <- round(solve(A), 1)

In [32]:
A.inv %*% B

[,1] [,2]
[1,] 4.5  0   
[2,] 1.5  3

In [33]:
A.inv

[,1] [,2]
[1,] 0.0   0.3
[2,] 0.5  -0.2

In [34]:
solve(A, B)

[,1] [,2]
[1,] 5    0   
[2,] 2    3

In [39]:
 ?qr

In [44]:
install.packages("matlib")

Warning message:
"dependency 'rgl' is not available"

package 'matlib' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\MarcosRoberto\AppData\Local\Temp\RtmpKM2Z8S\downloaded_packages


In [46]:
library(matlib)

Warning message:
"package 'matlib' was built under R version 3.6.3"

ERROR: Error: package or namespace load failed for 'matlib' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'rgl'


In [47]:
R.version

               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree          