In [9]:
A <- rbind(c(1,1,2), c(2, 4, -3), c(3, 6, -5))
AB <- rbind(c(1, 1, 2, 9), c(2, 4, -3, 1), c(3, 6, -5, 0))

In [8]:
A

[,1] [,2] [,3]
[1,] 1    1     2  
[2,] 2    4    -3  
[3,] 3    6    -5

In [10]:
AB

[,1] [,2] [,3] [,4]
[1,] 1    1     2   9   
[2,] 2    4    -3   1   
[3,] 3    6    -5   0

In [15]:
qr(A)$rank

[1] 3

In [16]:
qr(AB)$rank

[1] 3

In [17]:
solve(A)

[,1] [,2] [,3]
[1,]  2   -17  11  
[2,] -1    11  -7  
[3,]  0     3  -2

In [32]:
A <- rbind(c(1,2,1,1), c(0,1,1,1), c(2,2,0,0), c(1,0,-1,1))
AB <- rbind(c(1,2,1,1,0), c(0,1,1,1,1), c(2,2,0,0,-2), c(1,0,-1,1,-1))

In [33]:
A

[,1] [,2] [,3] [,4]
[1,] 1    2     1   1   
[2,] 0    1     1   1   
[3,] 2    2     0   0   
[4,] 1    0    -1   1

In [34]:
AB

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2     1   1     0  
[2,] 0    1     1   1     1  
[3,] 2    2     0   0    -2  
[4,] 1    0    -1   1    -1

In [35]:
qr(A)$rank

[1] 3

In [36]:
qr(AB)$rank

[1] 3

In [37]:
dim(A)

[1] 4 4

In [3]:
A <- rbind(c(1,1), c(0,1), c(0,4))
AB <- rbind(c(1,1,1), c(0,1,2), c(0,4,3))

In [8]:
qr(A)$rank

[1] 2

In [10]:
qr(AB)$rank

[1] 3