In [7]:
import numpy as np

In [10]:
# This is not a matrix, it is a list
row = list(range(3))
type(row)

list

In [3]:
M = [list(range(1,3)), list(range(3,5))]
M

[[1, 2], [3, 4]]

In [14]:
row = np.array([1,2,3])
print(row)
print(type(row))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
col = np.array([[1], [2], [3]])
col

array([[1],
       [2],
       [3]])

In [15]:
print(type(col))

<class 'numpy.ndarray'>


In [4]:
M[1]

[3, 4]

In [5]:
M[0][1]

2

In [8]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
 M[0]

array([1, 2, 3])

In [18]:
M[1:,]

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
N = np.diag(list(range(1,5)))
N

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(N)

array([1, 2, 3, 4])

In [27]:
np.shape(N)

(4, 4)

In [29]:
# Matrix sum
np.sum(M)

45

In [30]:
np.sum(M, axis=0)

array([12, 15, 18])

In [33]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(np.sum(M, axis=1))

[ 6 15 24]


In [35]:
np.prod(M)

362880

In [36]:
np.mean(M)

5.0

In [37]:
np.mean(M, axis=0)

array([4., 5., 6.])

In [38]:
np.mean(M, axis=1)

array([2., 5., 8.])

In [39]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(M.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [43]:
M.trace()

15

In [44]:
M.transpose().trace()

15

In [51]:
A = np.matrix([[1,2,3], [4,5,6]])
B = A * 2

In [52]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [54]:
print(A + B)

[[ 3  6  9]
 [12 15 18]]


In [57]:
5 * A

matrix([[ 5, 10, 15],
        [20, 25, 30]])

In [63]:
print(A.shape)
print(B.transpose().shape)

(2, 3)
(3, 2)


In [69]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [71]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [74]:
print(A*B)
print(B*A)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [75]:
# Matrix product is not conmutative. 
print(A.dot(B))
print(B.dot(A))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [76]:
# To raise a matris to a power we use a sublibrary of numpay called linalg
np.linalg.matrix_power(A, 2)

array([[ 7, 10],
       [15, 22]])

In [77]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [78]:
np.linalg.matrix_rank(A)

2

In [79]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [80]:
np.linalg.inv(B)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [88]:
A.dot(np.linalg.inv(A)).round(0) == np.linalg.inv(A).dot(A).round(0)

array([[ True,  True],
       [ True,  True]])

In [90]:
A.dot(np.linalg.inv(A)).round(0)

array([[1., 0.],
       [0., 1.]])

In [91]:
A

array([[1, 2],
       [3, 4]])

In [92]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [93]:
np.linalg.matrix_rank(A)

2