In [1]:
row = matrix(c(1,2,3,4), nrow = 1)
row

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4

In [3]:
A = matrix(1:12, nrow = 4)
A

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [15]:
dim(A) <- c(3, 4)
A

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [20]:
B <- cbind(1:3, 1:3)
B

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3

In [21]:
B <- cbind(B, 3:1)
B

[,1] [,2] [,3]
[1,] 1    1    3   
[2,] 2    2    2   
[3,] 3    3    1

In [30]:
B <- rbind(B, 3:1)
B

[,1] [,2] [,3]
[1,] 1    1    3   
[2,] 2    2    2   
[3,] 3    3    1   
[4,] 3    2    1   
[5,] 3    2    1

In [23]:
B[1,1]

[1] 1

In [24]:
 B[1,]

[1] 1 1 3

In [25]:
B[,1]

[1] 1 2 3 3

In [33]:
B[c(1:3),]

[,1] [,2] [,3]
[1,] 1    1    3   
[2,] 2    2    2   
[3,] 3    3    1

In [36]:
O <- matrix(0, nrow = 3, ncol = 3)
O

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

In [37]:
ones <- matrix(1, nrow = 3, ncol = 3)
ones

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

In [38]:
# Diagonal matrix

E <- diag(1:5)
E

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [40]:
# Get diagonal's matrix
A
diag(A)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 1 5 9

In [45]:
D <- matrix(1:9, nrow = 3)
D
diag(D)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 1 5 9

In [50]:
# Number of files and columns of a matrix
ncol(A)
nrow(A)
attributes(A)$dim
dim(A)

[1] 4

[1] 3

[1] 3 4

[1] 3 4

In [51]:
# Add each element
sum(A)

[1] 78

In [53]:
A
rowSums(A)
colSums(A)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 22 26 30

[1]  6 15 24 33

In [54]:
# Multiply each element
prod(A)

[1] 479001600

In [55]:
mean(A)

[1] 6.5

In [56]:
rowMeans(A)
colMeans(A)

[1] 5.5 6.5 7.5

[1]  2  5  8 11

In [57]:
A

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [58]:
t(A)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [61]:
diag(A)
sum(diag(A))

[1] 1 5 9

[1] 15

In [66]:
B <- A + 1
A
B
A + B
B + A

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 2    5     8   11  
[2,] 3    6     9   12  
[3,] 4    7    10   13

[,1] [,2] [,3] [,4]
[1,] 3     9   15   21  
[2,] 5    11   17   23  
[3,] 7    13   19   25

[,1] [,2] [,3] [,4]
[1,] 3     9   15   21  
[2,] 5    11   17   23  
[3,] 7    13   19   25

In [67]:
5 * A

[,1] [,2] [,3] [,4]
[1,]  5   20   35   50  
[2,] 10   25   40   55  
[3,] 15   30   45   60

In [75]:
dim(A)
dim(t(A))
A
t(A)
A %*% t(A)
t(A) %*% A

[1] 3 4

[1] 4 3

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

[,1] [,2] [,3]
[1,] 166  188  210 
[2,] 188  214  240 
[3,] 210  240  270

[,1] [,2] [,3] [,4]
[1,] 14    32   50   68 
[2,] 32    77  122  167 
[3,] 50   122  194  266 
[4,] 68   167  266  365

In [76]:
A+B == B+A 

[,1] [,2] [,3] [,4]
[1,] TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE

In [78]:
A1 <- matrix(1:9, nrow = 3)
A2 <- matrix(1:9, nrow = 3, byrow = TRUE)
A1
A2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [80]:
A1 %*% A2 == A2 %*% A1

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE

In [83]:
# Install packages
install.packages("Biodem")

package 'Biodem' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\MarcosRoberto\AppData\Local\Temp\RtmpE1tDQu\downloaded_packages


In [97]:
Biodem::mtx.exp(A1, 1)
Biodem::mtx.exp(A1, 2)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [92]:
install.packages("expm")

package 'expm' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\MarcosRoberto\AppData\Local\Temp\RtmpE1tDQu\downloaded_packages


In [94]:
library(expm)

In [96]:
A1%^%2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [99]:
rankMatrix(A1)

[1] 2
attr(,"method")
[1] "tolNorm2"
attr(,"useGrad")
[1] FALSE
attr(,"tol")
[1] 6.661338e-16

In [1]:
qr(A)$rank

ERROR: Error in qr(A): object 'A' not found


In [101]:
solve(A1)

ERROR: Error in solve.default(A1): Lapack routine dgesv: system is exactly singular: U[3,3] = 0


In [109]:
A <- cbind(c(1,-2,-1), c(1,1,1), c(-3,-1,-4))
# solve(M) calcs the matrix inverse if exist.
solve(A)

[,1]      [,2]       [,3]      
[1,] 0.4285714 -0.1428571 -0.2857143
[2,] 1.0000000  1.0000000 -1.0000000
[3,] 0.1428571  0.2857143 -0.4285714

In [113]:
round(A%*%solve(A), 0)
round(solve(A)%*%A, 0)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [5]:
A <- matrix(1:9, nrow = 3)
A

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
diag(c(1,2,3))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3